### ISSUE TITLE
Update via occ yields "sh: line 1: … cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by nursoda** [nextcloud/talk_matterbridge#50] opened 2021-06-02 16:49 UTC
I just did a `sudo -u http php occ app:update talk_matterbridge` and got
```
talk_matterbridge new version available: 1.22.3
sh: line 1: apps/talk_matterbridge/bin/matterbridge-1.22.2-linux-arm64: cannot execute binary file: Exec format error
talk_matterbridge updated
```
`ls la apps/talk_matterbridge/bin` shows that all binaries are there (note: why different execution rights?):
```
insgesamt 135884
-rw-r--r-- 1 http http 42881024  2. Jun 18:41 matterbridge-1.22.2-linux-32bit
-rwxr-xr-x 1 http http 49799168  2. Jun 18:41 matterbridge-1.22.2-linux-64bit
-rwxr-xr-x 1 http http 46465024  2. Jun 18:41 matterbridge-1.22.2-linux-arm64
```
The 'bug' is: Why does sh try to execute the arm64 binary on an amd64 system?

**Comment by gary-kim** [comment] 2021-06-02 17:21
This is working as intended. This is how the app identifies if it is running on a `x86` or `arm64` system. The different execution rights are because execution rights are not required on the 32 bit version as the app has already figured out that it is running on a 64 bit system.

Duplicate of #30

**Closed by gary-kim** 2021-06-02 17:21 UTC

**Comment by nursoda** [comment] 2021-06-02 20:12
👍 Sorry for only scanning the open issues and not the closed ones.
