### ISSUE TITLE
.toml file is overwritten when trying to update SkipTLSVerify=true

### ISSUE THREAD

**Issue by greavette** [nextcloud/talk_matterbridge#59] opened 2021-07-14 01:13 UTC
Hello,

I'm using talk_matterbridge version 1.22.4 on my Nextclout 21.0.3.  I've created the necessary config for XMPP but when I try and connect to my ejabberd server I receive a start: starttls handshake: x509: certificate error.  I then found the .toml file for talk_materbridge and set SkipTLSVerify=true.  But upon enabling the bridge (checkbox), the SkipTLSVerify setting is set back to false. 

Please assist with how I can update this setting in the .toml file without it being overwritten when starting this bridge?

Thank you.

**Comment by gary-kim** [comment] 2021-07-14 03:53
Duplicate of https://github.com/nextcloud/spreed/issues/5568

**Closed by gary-kim** 2021-07-14 03:53 UTC
