### ISSUE TITLE
talk_matterbridge tries to install arm

### ISSUE THREAD

**Issue by gpgmailencrypt** [nextcloud/talk_matterbridge#30] opened 2021-02-05 16:17 UTC
Hi,

I tried to update talk_matterbridge to version 1.22.0 and got the following error
CPU is a Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz and OS is Ubuntu 18.04
```
sudo -u www-data php ./occ app:update --all
[sudo] password for xxx: 
talk_matterbridge new version available: 1.22.0
sh: 1: /var/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.0-linux-arm64: Exec format error
talk_matterbridge updated
```
Deinstalling and reinstalling didn't help:
```
sudo -u www-data php ./occ app:install talk_matterbridge
sh: 1: /var/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.0-linux-arm64: Exec format error
sh: 1: /var/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.0-linux-arm64: Exec format error
talk_matterbridge 1.22.0 installed
sh: 1: /var/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.0-linux-arm64: Exec format error
```

**Comment by juliusbr** [comment] 2021-02-05 16:41
I have the same problem, running 

`sudo -u www-data php occ config:app:set spreed matterbridge_binary --value="/var/www/nextcloud/apps/talk_matterbridge/bin/matterbridge-1.22.0-linux-64bit"
`
seems to help, although if i run "occ maintenance:repair" it tries to start the arm version. I did't had the time to test it yet, but in Talk it claims to be running now.

**Comment by gary-kim** [comment] 2021-02-05 23:10
The error message that comes up during the install is fine. It just uses that to confirm whether your system is an arm64 system or amd64 system.
If Talk is not using the executable properly after, that's a bug. Let me know if Talk still fails to use Matterbridge.

**Comment by gary-kim** [comment] 2021-02-16 11:46
Closing as not a bug for now. Feel free to reopen if you think there's something else we could do.

**Closed by gary-kim** 2021-02-16 11:46 UTC

**Comment by tcitworld** [comment] 2022-07-24 11:15
We could redirect `stderr` to `/dev/null` when testing the binary. The version number is sent to `stdout`.

**Comment by Luticus** [comment] 2022-08-14 03:29
This error seems super annoying though because it seems to make the install take much longer than it should. Like rather than waiting for a binary to time out, cant it just do a uname -r and take the amd64 at the end as a sign that it's an amd64 system and not arm?
